services:
  - type: web
    name: lenscape
    env: node
    buildCommand: npm run build
    startCommand: npx serve dist
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
