services:
  - type: web
    name: lenscape
    env: node
    buildCommand: npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /.* 
        destination: /index.html
